const MOTION_FORCE_SEED_SOURCE = 'seed:motion-force';
const MOTION_FORCE_SEED_PACK_ID = 'seed-motion-force';
const MOTION_FORCE_SEED_NAME = 'motion-force';

const MOTION_FORCE_SEED_RELATIONSHIPS = [
  ['motion', 'position', 'uses_concept'],
  ['motion', 'reference point', 'uses_concept'],
  ['distance', 'displacement', 'commonly_confused_with'],
  ['displacement', 'direction', 'related_to'],
  ['speed', 'velocity', 'related_to'],
  ['velocity', 'displacement', 'uses_concept'],
  ['velocity', 'time', 'uses_concept'],
  ['acceleration', 'velocity', 'uses_concept'],
  ['acceleration', 'time', 'uses_concept'],
  ['negative acceleration', 'deceleration', 'related_to'],
  ['negative acceleration', 'acceleration', 'related_to'],
  ['force', 'motion', 'related_to', 'can change'],
  ['balanced forces', 'net force', 'uses_concept'],
  ['balanced forces', '0 net force', 'related_to', 'net force'],
  ['unbalanced forces', 'net force', 'uses_concept'],
  ['unbalanced force', 'acceleration', 'related_to', 'causes'],
  ['unbalanced force', 'change in motion', 'related_to', 'causes'],
  ['balanced forces', 'object at rest', 'related_to'],
  ['unbalanced forces', 'motion', 'related_to'],
  ['net force', "Newton's second law", 'uses_concept'],
  ["Newton's first law", 'inertia', 'related_to'],
  ['inertia', 'mass', 'related_to', 'increases with'],
  ["Newton's first law", 'unbalanced forces', 'uses_concept'],
  ["Newton's second law", 'F = ma', 'uses_formula'],
  ["Newton's second law", 'F = m × a', 'uses_formula', 'formula'],
  ['unbalanced force', "Newton's second law", 'prerequisite_for'],
  ['friction', 'motion', 'related_to', 'opposes'],
  ['air resistance', 'motion through air', 'related_to', 'opposes'],
  ['gravity', 'Earth', 'related_to', 'pulls objects toward'],
  ['terminal velocity', 'gravity and air resistance are balanced', 'related_to', 'occurs when'],
  ["Newton's third law", 'action-reaction forces', 'related_to', 'equal and opposite'],
  ['momentum', 'mass in motion', 'related_to', 'is'],
  ['conservation of momentum', 'momentum transferred in collision', 'related_to', 'means'],
  ['mass', 'weight', 'commonly_confused_with', 'different from'],
  ['weight', 'force of gravity', 'related_to', 'is'],
  ['distance-time graph', 'speed', 'related_to'],
  ['velocity-time graph', 'acceleration', 'related_to']
];

const MOTION_FORCE_SEED_NODE_TYPES = {
  distance: 'vocabulary',
  displacement: 'vocabulary',
  direction: 'concept',
  motion: 'vocabulary',
  position: 'concept',
  'reference point': 'vocabulary',
  speed: 'vocabulary',
  velocity: 'vocabulary',
  time: 'concept',
  acceleration: 'concept',
  'negative acceleration': 'vocabulary',
  deceleration: 'vocabulary',
  force: 'vocabulary',
  'balanced forces': 'vocabulary',
  'unbalanced forces': 'vocabulary',
  'net force': 'vocabulary',
  '0 net force': 'concept',
  'object at rest': 'concept',
  'newtons first law': 'concept',
  inertia: 'vocabulary',
  mass: 'vocabulary',
  'newtons second law': 'concept',
  'f ma': 'formula',
  'f m a': 'formula',
  'unbalanced force': 'concept',
  'change in motion': 'concept',
  friction: 'vocabulary',
  'air resistance': 'vocabulary',
  'motion through air': 'concept',
  gravity: 'vocabulary',
  earth: 'concept',
  'terminal velocity': 'vocabulary',
  'gravity and air resistance are balanced': 'concept',
  'newtons third law': 'concept',
  'action reaction forces': 'concept',
  momentum: 'vocabulary',
  'mass in motion': 'concept',
  'conservation of momentum': 'concept',
  'momentum transferred in collision': 'concept',
  weight: 'vocabulary',
  'force of gravity': 'concept',
  'distance time graph': 'concept',
  'velocity time graph': 'concept'
};

module.exports = {
  MOTION_FORCE_SEED_SOURCE,
  MOTION_FORCE_SEED_PACK_ID,
  MOTION_FORCE_SEED_NAME,
  MOTION_FORCE_SEED_RELATIONSHIPS,
  MOTION_FORCE_SEED_NODE_TYPES
};
